name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: registry.pocapi.in
        username: ${{ secrets.REGISTRY_UNAME }}
        password: ${{ secrets.REGISTRY_PWD }}
        
    - name: docker build api
      run: |
        docker build -t daikin_checksheetportal_api .
    - name: docker tag api
      run: |
        docker tag daikin_checksheetportal_api registry.pocapi.in/daikin_checksheetportal_api
    - name: docker tag api
      run: |
        docker push registry.pocapi.in/daikin_checksheetportal_api
    - name: deploy api to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER_IP }}
        username: root
        password: ${{ secrets.SSH_SERVER_PWD }}
        port: 22
        script: |
          docker pull registry.pocapi.in/daikin_checksheetportal_api
          cd /data/moovtelecom-bac-dockercompose
          docker-compose -f checksheetapi.docker-compose.yml --env-file dev-global-variables.env up -d
